"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Provider from './components/providers/SessionProvider'
import { NextUIProvider } from '@nextui-org/react'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <Provider>
            <Header />
            {children}
          </Provider>
        </NextUIProvider>
      </body>
    </html>
  )
}
